In [1]:
import pickle
import numpy as np
import pandas as pd

In [111]:
pk= pickle.load(open('adj_mx_gang.pkl','rb'))
df = pd.read_csv('gang_csv.csv')

In [3]:
adj_info = pd.read_csv('distances_gang.csv')

In [20]:
pk[2]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

### Directed Graphical Causal Models
 - (1) a set of variables, regarded as “random variables," 
 - (2) a set of directed edges between pairs of variables, each edge regarded as the hypothesis that the two variables would be associated if all other variables were fixed at some values while the tail variable is exogenously varied, and 
 - (3) a joint probability distribution over the possible values of all of the variables
 
  
 - 일반적으로 "구조 방정식 모델"(SEM) 또는 기능 인과 모델(FCM)로 표시되는 DGCM의 클래스는 각 변수의 값이 그래프에서 직접 원인과 측정되지 않은 장애의 결정론적 함수라고 가정한다.
 - 선형 모형이 가장 일반적이지만 변수를 직접 원인과 연결하는 함수는 어떤 것이든 될 수 있다
 - DGCM의 두 번째 구성요소는 지시된 그래프가 인과적 평균을 갖는 데 필수적이다
 - The causal Bayesian network was defined in a similar way by Pearl (2000, p.23). 

In [110]:
adj_info[adj_info['from'] == 1210030000]

from          to  cost
0  1210030000  1210030000     0

In [31]:
adj_info[adj_info['from'] == 1220032200]['to'].unique()

array([1220029600, 1220032300, 1220030400, 1220031300, 1220033600,
       1220034300, 1220033000, 1220035300], dtype=int64)

In [43]:
edges = df.columns

In [87]:
edges

Index(['1220029700', '1220032100', '1220033000', '1220024600', '1220028200',
       '1210030000', '1220025300', '1220029200', '1220034000', '1220034300',
       '1220027500', '1220034200', '1220026100', '1220033700', '1220026700',
       '1220035900', '1220031900', '1220035300', '1220032600', '1220034500',
       '1220030400', '1220033500', '1220030000', '1220029600', '1220024000',
       '1220026600', '1220030900', '1220031100', '1220034700', '1220031200',
       '1220028100', '1220031300', '1220028300', '1220030100', '1220033600',
       '1220029100', '1220032300', '1220032000', '1220032200', '1220034100',
       '1220029800', '1220027400', '1220027200', '1220029000', '1220026200',
       '1220029300', '1220032900', '1220029900', '1220026300', '1220033400',
       '1220025200', '1220033100', '1220031800', '1220033300', '1220031000',
       '1220034600', '1220032800', '1220026800'],
      dtype='object')

In [88]:
edges_index = {}

In [89]:
for i in range(len(edges)):
    edges_index[str(edges[i])] = i

In [105]:
type(edges_index)

dict

In [106]:
with open('edges_index.pickle','wb') as fw:
    pickle.dump(edges_index, fw)

In [91]:
adj_matrix = pk[2]

In [92]:
for i in range(58):
    for j in range(58):
        adj_matrix[i][j] = 0

In [93]:
adj_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
adj_edges = adj_info[adj_info['from'] == edge]['to'].unique()

In [96]:
for edge in edges:
    adj_edges = adj_info[adj_info['from'] == int(edge)]['to'].unique()
    for adj in adj_edges:
        adj_matrix[edges_index[str(edge)]][edges_index[str(adj)]] = 1

In [97]:
sum(adj_matrix)

array([12., 17., 12., 12., 16.,  1.,  9., 12.,  8., 12., 12., 12., 12.,
        9.,  5.,  8., 12., 12.,  9.,  9., 13., 15., 12., 13.,  9., 10.,
       12., 13., 12., 17., 10., 13., 12., 13., 12., 16., 13., 15.,  9.,
       12., 17., 16., 12., 13., 12., 10., 15., 16.,  9., 12., 12., 17.,
       12., 12., 15.,  8., 12., 10.], dtype=float32)

In [98]:
for i in range(len(edges_index)):
    adj_matrix[i][i] = 0

In [99]:
adj_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [101]:
sum(adj_matrix)

array([12., 16., 12., 12., 16.,  0.,  8., 12.,  8., 12., 12., 12., 11.,
        8.,  4.,  7., 11., 11.,  9.,  9., 13., 15., 12., 13.,  9., 10.,
       12., 12., 12., 17.,  9., 12., 11., 13., 12., 16., 13., 15.,  9.,
       12., 17., 16., 12., 13., 12., 10., 14., 15.,  9., 11., 12., 17.,
       12., 11., 15.,  8., 12., 10.], dtype=float32)

In [102]:
np.save("adj_matrix.npy", adj_matrix)

In [103]:
np.save("edges_index.npy", edges_index)