## Network Properties: How to Measure a Network

1. Degree Distribution (P(k))
  - graph에서 random으로 node를 뽑았을때 그 node의 degree(edge의 수?) k 일 확률분포
2. Path length (h)
  - distance, diameter(max path distance), avg path length(inf 무시)
3. Cluster Coefficient (C)
  - $node_i$에 대해 연결된 node들과 잘 연결되어 있는가를 표시하는 지수
  - $C_i = 2e_i / k_i(k_i - 1)$($e_i$ is number of edges between the neighbors of node i, $k_i$ is degree of $node_i$)
4. Connected component (s)
  - 가장 큰 component의 크기
  - 한 node를 잡고 BFS를 반복해서 연결된 노드를 모두 지나고, 모든 노드를 지났다면 안 지난 node하나를 선택해서 또 BFS를 반복해 크기를 구한다.


## ErdosRenyi Random Graph Model
1. G_np : n개의 node가 있을 때 임의의 두 node사이에 edge가 존재할 확률 p로 iid 한것
  - $P(k) = n-1C_k * p^k * (1-p)^{n-1-k}$
  - $E[C_i] := p = k/n$ 
  - distance: Expansion alpha : 전체 노드를 두 부분으로 나누었을때 더 작은 부분에서 큰 부분으로 가는 최소의 edge수 

2. G_nm : n개의 node m개의 edge가 있을 때, 그 m개의 edge가 uniform하게 random으로 존재. G_nm : n개의 node m개의 edge가 있을 때, 그 m개의 edge가 uniform하게 random으로 존재 

(real world와 random world를 비교해 보았을 때 n 이 커짐에 따라 real world의 묘사가 어려워진다.)(degree distribution, avg.clustering coef 가 다름)

## Small world model

1. Low-dimensional regular lattice 를 생성한다. 이는 주변노드끼리만 이어져있는 네트워크를 의미한다. 즉, High clustering이고 따라서 High diameter이다.

2. Rewire : 주변 노드와의 연결을 일정 확률 p 로 끊고, 아무 노드와 연결한다. 이런 연결이 생길 때마다 shortcut이 생기는 것이다. 즉, diameter가 점점 작아진다. 반면 clustering은 점점 낮아질 것이다.

(high clustering, low diameter을 만들어 좀 더 real world 와 비슷하게 만든다. 
하지만, degree distribution은 여전히 real network와는 다르다.)  

## kronecker Graph

idea : recursive model of network structure

- define a kronecker product of two graphs as a kronecker product of their adjacency matrices
- kroneker graph is obtained by growing seuence of graphs

In [1]:
# kronecker graph MLE 구현
import numpy as np
G = [[1,0,1,1],[0,1,0,1],[1,0,1,1],[1,1,1,1]]
KM = [[0.5,0.2],[0.1,0.3]]
KM = np.kron(KM, KM)
print(KM)
P = 1
for i in range(KM.shape[0]):
  for j in range(KM.shape[1]):
    # G에 속할 때.
    if G[i][j]==1:
      P = P*KM[i][j]
    # G에 속하지 않을 때.
    else:
      P = P*(1-KM[i][j])
# P는 kronecker 로부터 생성된 그래프가 실제 G일 확률을 나타냄.
print(P)

[[0.25 0.1  0.1  0.04]
 [0.05 0.15 0.02 0.06]
 [0.05 0.02 0.15 0.06]
 [0.01 0.03 0.03 0.09]]
2.6937563310000008e-15
