In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('C:/Users/chanyoung/Desktop/Neural-GC-master/lorenz_96_10_10_1000.csv')
X = df[['a','b']]

In [3]:
X

a         b
0    0.099017  2.902559
1    2.383257  4.356706
2    6.123711  5.586561
3    8.790827  4.554719
4    8.670151  2.439085
..        ...       ...
995 -2.359435 -1.151973
996 -2.137420  0.945424
997 -0.803815  1.656646
998  0.199564  2.456403
999  0.209665  3.018126

[1000 rows x 2 columns]

In [15]:
input_cause = []
input_target = []
output_target = []
x_columns = X.columns
for i in range(len(X) - (10 + 1)):
    input_cause.append(X["a"].values[i: i + 10])

In [16]:
input_cause

[array([ 0.09901663,  2.38325721,  6.12371096,  8.79082668,  8.67015136,
         8.39568701,  6.37542044,  0.78873943, -3.03152157, -3.00095352]),
 array([ 2.38325721,  6.12371096,  8.79082668,  8.67015136,  8.39568701,
         6.37542044,  0.78873943, -3.03152157, -3.00095352, -1.97711461]),
 array([ 6.12371096,  8.79082668,  8.67015136,  8.39568701,  6.37542044,
         0.78873943, -3.03152157, -3.00095352, -1.97711461, -1.64289106]),
 array([ 8.79082668,  8.67015136,  8.39568701,  6.37542044,  0.78873943,
        -3.03152157, -3.00095352, -1.97711461, -1.64289106, -1.64461997]),
 array([ 8.67015136,  8.39568701,  6.37542044,  0.78873943, -3.03152157,
        -3.00095352, -1.97711461, -1.64289106, -1.64461997, -1.70822178]),
 array([ 8.39568701,  6.37542044,  0.78873943, -3.03152157, -3.00095352,
        -1.97711461, -1.64289106, -1.64461997, -1.70822178, -1.45933914]),
 array([ 6.37542044,  0.78873943, -3.03152157, -3.00095352, -1.97711461,
        -1.64289106, -1.64461997, -1.70

In [18]:
import torch
import torch.nn as nn
nn.Parameter(torch.Tensor(5, 10))

Parameter containing:
tensor([[2.9514e+29, 1.9012e-19, 4.9657e+28, 1.3409e+13, 1.4591e-19, 1.8987e+28,
         7.1061e+31, 4.2964e+24, 1.8525e+28, 7.5018e+28],
        [9.7754e-03, 4.4721e+21, 7.3714e+28, 4.5453e+30, 1.8994e-19, 1.9441e+31,
         1.1727e-19, 3.0247e+24, 1.3895e-11, 1.8617e+25],
        [1.2708e+31, 4.2961e+24, 1.8016e+25, 1.8465e+25, 8.3986e-33, 1.8710e+14,
         2.1174e-13, 2.1459e+20, 9.2489e-04, 1.7537e+19],
        [1.1628e+27, 1.4244e-13, 2.0618e-19, 2.2871e+20, 6.6135e+19, 1.2406e+22,
         2.8573e+32, 1.5051e-13, 6.6554e-33, 3.0981e+32],
        [2.0619e-19, 7.2053e+22, 4.7428e+30, 1.8522e+28, 1.8057e+28, 1.9603e-19,
         1.9432e-19, 1.7260e+25, 2.0616e-19, 1.8493e+20]], requires_grad=True)

In [24]:
nn.Parameter(torch.tensor(input_cause))[0]

tensor([ 0.0990,  2.3833,  6.1237,  8.7908,  8.6702,  8.3957,  6.3754,  0.7887,
        -3.0315, -3.0010], dtype=torch.float64, grad_fn=<SelectBackward>)

In [21]:
clusters = torch.tensor()
stds = torch.tensor()

TypeError: tensor() missing 1 required positional arguments: "data"

In [23]:
torch.zeros(10)[0]

tensor(0.)

In [25]:
nn.Parameter(torch.zeros(14,5))

Parameter containing:
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], requires_grad=True)

In [32]:
a = torch.zeros(2)

In [33]:
b = torch.zeros(2,1)

In [38]:
torch.mul(b,a)

tensor([[0., 0.],
        [0., 0.]])

In [43]:
b.mul(a.T)

tensor([[0., 0.],
        [0., 0.]])

In [47]:
torch.mm(a,b)

RuntimeError: self must be a matrix

In [48]:
b = torch.tensor([0,1,2])
a = torch.tensor([1,2,3])

In [50]:
a*b

tensor([0, 2, 6])

In [51]:
m = nn.Linear(20, 30)
input_ = torch.randn(128, 20)
output = m(input_)
print(output.size())


torch.Size([128, 30])


In [58]:
output

tensor([[-0.8627,  0.5814, -0.3299,  ...,  0.1563,  0.2784, -0.0889],
        [-0.2981,  0.2903, -0.6282,  ...,  0.2263, -0.5486,  0.1973],
        [-0.6995,  1.2299,  0.2233,  ...,  0.6372, -0.2566, -0.5159],
        ...,
        [-0.2507, -0.1697, -0.1226,  ..., -0.0147, -0.9851, -1.1377],
        [-0.4057,  0.4353,  0.0232,  ...,  0.1229, -0.0845, -0.4668],
        [ 0.7388, -0.8640,  0.2018,  ...,  0.8054,  0.6059, -0.4706]],
       grad_fn=<AddmmBackward>)

In [57]:
torch.cat((a,b),0)

tensor([1, 2, 3, 0, 1, 2])