In [22]:
import numpy as np
import pandas as pd
import pickle
import math
import pandas as pd
from pandas import HDFStore 
import argparse

###################################################################################
#location
node_ids_filename = 'data/node_locate.txt'
with open(node_ids_filename) as f:
    _node_ids = f.read().strip()
    _node_ids = _node_ids.replace('\n', ' ')
    _node_ids = _node_ids.split(' ')

node_id = []
node_ids = []
node_name = []
node_loc = []
for i in range(len(_node_ids)):
    if(_node_ids[i] == ''):
        continue
    node_id.append(_node_ids[i])

for i in range(len(node_id)):
    if(i <= 4):
        continue
    if(node_id[i] == 'C'):
        continue
    node_ids.append(node_id[i])
for i in range(len(node_ids)):
    if(i % 4 == 0):
        line = []
        node_name.append(node_ids[i])
        line.append(node_ids[i+1])
        line.append(node_ids[i+2])
        line.append(node_ids[i+3])
        node_loc.append(line)
node_loc=np.array(node_loc).astype('float32')
print("node_loc",node_loc.shape)

###################################################################################
#save to npy file
np.save('data/node_signal', _node_signal)
np.save('data/node_loc', node_loc)

_node_signal (135, 106, 7)
node_loc (106, 3)
-118.45 139.457
-31.3102 21.6857
-563.119 91.0359
-0.0160272 0.000982589
-0.0147581 0.0163793
-0.00474041 0.0034676
0.0 0.0


In [1]:
import numpy as np
import pandas as pd
import pickle
import math
import pandas as pd
from pandas import HDFStore 
import argparse
import matplotlib.pyplot as plt

####################################################################################
node_loc=np.load('data/node_loc.npy')
n_nodes=node_loc.shape[0]
node_id = [str(i) for i in range(1,1+n_nodes)]
node_id_to_ind = {}
for i, node in enumerate(node_id, 1):
    node_id_to_ind[node] = i
num_node = len(node_id)

#element 1################
node_link_filename = 'data/raw_data/element1.txt'
link_mx = np.zeros((num_node, num_node), dtype=np.float32)
with open(node_link_filename) as f:
    _node_link = f.read().strip()
    _node_link = _node_link.replace('\n', ' ')
    _node_link = _node_link.split(' ')

node_link = []
for i in range(len(_node_link)):
    if(_node_link[i] == ''):
        continue
    node_link.append(_node_link[i])

element_id = []

node_link = np.reshape(node_link, (-1, 6))
node_link = node_link.astype('int32')

link_mx = np.zeros((num_node, num_node), dtype=np.float32)
for i in range(39):
    link_mx[node_link[i][2]-1][node_link[i][3]-1] = node_link[i][1]
    link_mx[node_link[i][3]-1][node_link[i][2]-1] = node_link[i][1]
link_mx1_1=link_mx

link_mx = np.zeros((num_node, num_node), dtype=np.float32)
for i in range(39,node_link.shape[0]):
    link_mx[node_link[i][2]-1][node_link[i][3]-1] = node_link[i][1]
    link_mx[node_link[i][3]-1][node_link[i][2]-1] = node_link[i][1]    
link_mx1_2=link_mx

#element 2################
node_link_filename = 'data/raw_data/element2.txt'
link_mx = np.zeros((num_node, num_node), dtype=np.float32)
with open(node_link_filename) as f:
    _node_link = f.read().strip()
    _node_link = _node_link.replace('\n', ' ')
    _node_link = _node_link.split(' ')

node_link = []
for i in range(len(_node_link)):
    if(_node_link[i] == ''):
        continue
    node_link.append(_node_link[i])

element_id = []
node_link=[i for i in node_link if i.isdigit()]
node_link = np.reshape(node_link, (-1, 5))
node_link = node_link.astype('int32')
for i in range(node_link.shape[0]):
    link_mx[node_link[i][1]-1][node_link[i][2]-1] = node_link[i][1]
    link_mx[node_link[i][2]-1][node_link[i][1]-1] = node_link[i][1]
link_mx2=link_mx

#element 3################
node_link_filename = 'data/raw_data/element3.txt'
link_mx = np.zeros((num_node, num_node), dtype=np.float32)
with open(node_link_filename) as f:
    _node_link = f.read().strip()
    _node_link = _node_link.replace('\n', ' ')
    _node_link = _node_link.split(' ')

node_link = []
for i in range(len(_node_link)):
    if(_node_link[i] == ''):
        continue
    node_link.append(_node_link[i])

element_id = []

node_link = np.reshape(node_link, (-1, 6))
node_link = node_link.astype('int32')
for i in range(node_link.shape[0]):
    link_mx[node_link[i][2]-1][node_link[i][3]-1] = node_link[i][1]
    link_mx[node_link[i][3]-1][node_link[i][2]-1] = node_link[i][1]
link_mx3=link_mx

####################################################################################
link_mx=link_mx1_1+link_mx1_2+link_mx2+link_mx3
#np.save('data/link_mx', link_mx)
np.sum(link_mx1_1!=0),np.sum(link_mx1_2!=0),np.sum(link_mx2!=0),np.sum(link_mx3!=0)


####################################################################################
#adj matrix
#link_mx=np.load('data/link_mx.npy')
link_mx0=link_mx1_1+link_mx1_2+link_mx2+link_mx3
link_mx0=link_mx0+np.eye(106)
link_mx0[link_mx0!=0]=1

link_mx1_1=link_mx1_1+np.eye(106)#cross beam
link_mx1_1[link_mx1_1!=0]=1

link_mx1_2=link_mx1_2+np.eye(106)#girder
link_mx1_2[link_mx1_2!=0]=1

link_mx2=link_mx2+np.eye(106)#cable
link_mx2[link_mx2!=0]=1

link_mx3=link_mx3+np.eye(106)#tower
link_mx3[link_mx3!=0]=1

####################################################################################
#getting distance matrix
node_loc=np.load('data/node_loc.npy')
num_node=len(node_loc)
n_nodes=node_loc.shape[0]
dist_mx = np.zeros((num_node, num_node), dtype=np.float32)
dist_mx[:] = np.inf
for i in range(num_node):
    for j in range(num_node):
        x = float(node_loc[i][0]) - float(node_loc[j][0])
        y = float(node_loc[i][1]) - float(node_loc[j][1])
        z = float(node_loc[i][2]) - float(node_loc[j][2])
        x = math.pow(x,2)
        y = math.pow(y,2)
        z = math.pow(z,2)
        dis = math.sqrt(x+y+z)
        dist_mx[i, j] = dis
#distances = dist_mx[~np.isinf(dist_mx)].flatten()
# std = distances.std()
# adj_mx = np.exp(-np.square(dist_mx / std))
adj_mx=dist_mx

adj_mx0=adj_mx*link_mx0
print(adj_mx)

################################################
import collections
print(collections.Counter(adj_mx0.flatten()))

#cross beam-#girder-#cable-#tower
type_e=np.array([200000,200000,15800,200000])#type_e=np.array([210000,180000,140000,200000])
type_e=(type_e)#/np.max(type_e)
print(type_e,type_e.std(),adj_mx0.std())

link_mx1_1_e=link_mx1_1-np.eye(106)
link_mx1_1_e=link_mx1_1_e*type_e[0]#cross beam

link_mx1_2_e=link_mx1_2-np.eye(106)
link_mx1_2_e=link_mx1_2_e*type_e[1]#girder

link_mx2_e=link_mx2-np.eye(106)
link_mx2_e=link_mx2_e*type_e[2]#cable

link_mx3_e=link_mx3-np.eye(106)
link_mx3_e=link_mx3_e*type_e[3]#tower

adj_mx_e=link_mx1_1_e+link_mx1_2_e+link_mx2_e+link_mx3_e
print(adj_mx_e)

print(collections.Counter(adj_mx_e.flatten()))

[[     0.     6100.    12200.   ... 178678.1  179105.72 179582.45]
 [  6100.        0.     6100.   ... 172640.92 173083.48 173576.75]
 [ 12200.     6100.        0.   ... 166608.34 167066.88 167577.86]
 ...
 [178678.1  172640.92 166608.34 ...      0.     3000.     6000.  ]
 [179105.72 173083.48 167066.88 ...   3000.        0.     3000.  ]
 [179582.45 173576.75 167577.86 ...   6000.     3000.        0.  ]]
Counter({0.0: 10866, 6100.0: 152, 7500.0: 82, 3000.0: 32, 62562.05078125: 16, 50520.1953125: 16, 38810.4375: 16, 27854.802734375: 16, 19005.525390625: 16, 9000.0: 16, 10000.0: 8})
[200000 200000  15800 200000] 79760.9396885468 3727.836796625876
[[     0. 200000.      0. ...      0.      0.      0.]
 [200000.      0. 200000. ...      0.      0.      0.]
 [     0. 200000.      0. ...      0.      0.      0.]
 ...
 [     0.      0.      0. ...      0. 200000.      0.]
 [     0.      0.      0. ... 200000.      0. 200000.]
 [     0.      0.      0. ...      0. 200000.      0.]]
Counter({0.

In [2]:
adj_mx=[adj_mx0,adj_mx_e]
print(np.sum(adj_mx0==0)/(106*106))
print(np.sum(adj_mx_e==0)/(106*106))
########################################
output_pkl_filename='data/sensor_graph/adj_mx_type_e.pkl'
########################################
with open(output_pkl_filename, 'wb') as f:
    pickle.dump([[], [], adj_mx], f, protocol=2)

0.9670701317194731
0.9670701317194731


In [3]:
#####area
#cross beam
w=165.10;d=525.78;wt=8.89;ft=11.43;cb_a=(w*d)-(w-wt)*(d-2*ft);print(cb_a)#8245.14480000001
#girder
b=1000;h=1000;t=50;g_a=g_a=(b*h)-((b-t)*(h-t));print(g_a)#97500
#cable
c_a=3848.45#0
#tower
b=1000;h=2000;t=50;t_a=(b*h)-((b-t)*(h-t));print(t_a)#147500

#cross beam-#girder-#cable-#tower
type_a=np.array([cb_a,g_a,c_a,t_a])#type_e=np.array([210000,180000,140000,200000])
type_a=(type_a)#/np.max(type_a)
print(type_a,type_a.std())

link_mx1_1_a=link_mx1_1-np.eye(106)
link_mx1_1_a=link_mx1_1_a*type_a[0]#cross beam

link_mx1_2_a=link_mx1_2-np.eye(106)
link_mx1_2_a=link_mx1_2_a*type_a[1]#girder

link_mx2_a=link_mx2-np.eye(106)
link_mx2_a=link_mx2_a*type_a[2]#cable

link_mx3_a=link_mx3-np.eye(106)
link_mx3_a=link_mx3_a*type_a[3]#tower

adj_mx_a=link_mx1_1_a+link_mx1_2_a+link_mx2_a+link_mx3_a
print(collections.Counter(adj_mx_a.flatten()))

with open('data/sensor_graph/adj_mx_type_a.pkl', 'wb') as f:
    pickle.dump(adj_mx_a, f, protocol=2)

8245.14480000001
97500
147500
[  8245.1448  97500.       3848.45   147500.    ] 60870.793198336956
Counter({0.0: 10866, 97500.0: 152, 3848.45: 80, 8245.14480000001: 78, 147500.0: 60})
