In [10]:
import numpy as np

In [17]:
datas = np.load('data/data.npy')
targets = np.load('data/target.npy')
datas.shape, targets.shape

((10, 20, 20), (10, 20, 20))

In [15]:
state = np.zeros((20,20))
state.shape

(20, 20)

In [16]:
d = data[0]

In [59]:
def get_furniture_list(data):
    furnitures = {}
    for i in range(1, 17):
        furnitures[i] = [[]]
        for j in range(20):
            for k in range(20):
                if data[j][k] == i:
                    furnitures[i][j].append(data[j][k])
            furnitures[i].append([])

    for i in range(1, 17):
        for j in range(20, -1, -1):
            if len(furnitures[i][j]) == 0:
                del(furnitures[i][j])
            
    for i in range(16, 0, -1):
        if len(furnitures[i]) == 0:
            del(furnitures[i])
    
    for key in furnitures.keys():
        furnitures[key] = np.array(furnitures[key])
    
    return furnitures

In [63]:
furniture = get_furniture_list(d)

In [64]:
f = furniture[1]
f

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [72]:
furniture[7]

array([[7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7]])

In [67]:
for f in furniture.values():
    print(f.shape)

(7, 7)
(2, 2)
(2, 7)
(2, 9)


In [131]:
import copy

def get_mask(state, f):
    mask = np.ones((20,20))
    shape = f.shape
    
    zero_list = []
    for i in range(20):
        for j in range(20):
            if state[i][j] != 0:
                mask[i][j] = 0
            else:
                zero_list.append((i,j))
    
    temp_zero_list = copy.deepcopy(zero_list)
    for zero in zero_list:
        z_y, z_x = zero
        if z_y + shape[0] > 20 or z_x + shape[1] > 20:
            mask[z_y][z_x] = 0
            temp_zero_list.remove(zero)
            
    zero_list = copy.deepcopy(temp_zero_list)
    
    for zero in zero_list:
        z_y, z_x = zero
        
        for i in range(z_y, z_y + shape[0]):
            flag = False
            for j in range(z_x, z_x + shape[1]):
                if state[i][j] != 0:
                    mask[z_y][z_x] = 0
                    flag = True
                    break              
            if flag:
                break
            
    return mask

In [145]:
def print_numpy(arr):
    for i in range(20):
        for j in range(20):
            print('{:2d}'.format(int(arr[i][j])), end = ' ')
        print('')

In [82]:
furniture[1]

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [85]:
mask = get_mask(state, furniture[1])

In [84]:
def get_action_space(mask):
    action_space = []
    for i in range(20):
        for j in range(20):
            if mask[i][j] == 1:
                action_space.append((i,j))
                
    return action_space

In [86]:
action_space = get_action_space(mask)

In [90]:
import random

action = random.sample(action_space, 1)[0]
action

(10, 6)

In [91]:
def batch_object(state, furniture, action):
    f = furniture[0][0]
    shape = furniture.shape
    
    for i in range(action[0], action[0] + shape[0]):
        for j in range(action[1], action[1] + shape[1]):
            state[i][j] = f

In [93]:
batch_object(state, furniture[1], action)
print_numpy(state)

0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 
0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 
0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 
0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 
0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 
0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 
0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 


In [106]:
furniture[6]

array([[6, 6],
       [6, 6]])

In [132]:
mask = get_mask(state, furniture[6])

In [133]:
print_numpy(mask)

1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 
1 1 1 1 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 
1 1 1 1 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 
1 1 1 1 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 
1 1 1 1 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 
1 1 1 1 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 
1 1 1 1 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 
1 1 1 1 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 
1 1 1 1 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 


In [135]:
action_space = get_action_space(mask)
action = random.sample(action_space, 1)[0]
action

(3, 7)

In [136]:
batch_object(state, furniture[6], action)
print_numpy(state)

0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 6 6 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 6 6 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 
0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 
0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 
0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 
0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 
0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 
0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 


In [141]:
mask = get_mask(state, furniture[7])
action_space = get_action_space(mask)
action = random.sample(action_space, 1)[0]
action

(17, 4)

In [142]:
batch_object(state, furniture[7], action)
print_numpy(state)

0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 6 6 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 6 6 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 
0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 
0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 
0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 
0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 
0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 
0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 
0 0 0 0 7 7 7 7 7 7 7 0 0 0 0 0 0 0 0 0 
0 0 0 0 7 7 7 7 7 7 7 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 


In [143]:
mask = get_mask(state, furniture[11])
action_space = get_action_space(mask)
action = random.sample(action_space, 1)[0]
action

(0, 11)

In [146]:
batch_object(state, furniture[11], action)
print_numpy(state)

 0  0  0  0  0  0  0  0  0  0  0 11 11 11 11 11 11 11 11 11 
 0  0  0  0  0  0  0  0  0  0  0 11 11 11 11 11 11 11 11 11 
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 
 0  0  0  0  0  0  0  6  6  0  0  0  0  0  0  0  0  0  0  0 
 0  0  0  0  0  0  0  6  6  0  0  0  0  0  0  0  0  0  0  0 
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 
 0  0  0  0  0  0  1  1  1  1  1  1  1  0  0  0  0  0  0  0 
 0  0  0  0  0  0  1  1  1  1  1  1  1  0  0  0  0  0  0  0 
 0  0  0  0  0  0  1  1  1  1  1  1  1  0  0  0  0  0  0  0 
 0  0  0  0  0  0  1  1  1  1  1  1  1  0  0  0  0  0  0  0 
 0  0  0  0  0  0  1  1  1  1  1  1  1  0  0  0  0  0  0  0 
 0  0  0  0  0  0  1  1  1  1  1  1  1  0  0  0  0  0  0  0 
 0  0  0  0  0  0  1  1 

In [149]:
print_numpy(targets[0])

 1  1  1  1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0 
 1  1  1  1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0 
 1  1  1  1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0 
 1  1  1  1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0 
 1  1  1  1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0 
 1  1  1  1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0 
 1  1  1  1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0 
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 
 0  0  0  0  0  0  0  0 

In [152]:
d_pos_list = []
t_pos_list = []

for key, f in furniture.items():
    d_pos = (-1,-1)
    t_pos = (-1,-1)
    
    for i in range(20):
        flag = False
        for j in range(20):
            if state[i][j] == key:
                d_pos = (i,j)
                flag = True
                break
        if flag:
            break
            
    for i in range(20):
        flag = False
        for j in range(20):
            if targets[0][i][j] == key:
                t_pos = (i,j)
                flag = True
                break
        if flag:
            break
            
    d_pos_list.append(d_pos)
    t_pos_list.append(t_pos)

In [153]:
d_pos_list

[(10, 6), (3, 7), (17, 4), (0, 11)]

In [154]:
t_pos_list

[(0, 0), (18, 16), (18, 9), (18, 0)]

In [162]:
import math

def distance(p1, p2):
    return math.sqrt((p1[0]-p2[0])**2 + (p1[1]-p2[1])**2)

In [166]:
def calculate_reward(d_pos_list, t_pos_list):
    reward = 0
    
    for d, t in zip(d_pos_list, t_pos_list):
        reward += distance(d, t)
        
    return -reward

In [167]:
calculate_reward(d_pos_list, t_pos_list)

-55.34880209754827